version: "3.9"

services:
  db:
    image: postgres
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5435:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
